project:
  type: website

website:
  reader-mode: true
  open-graph: true
  title: "Zoe F. Elkins"
  navbar:
    background: primary
    search: true
    left:
      - href: about.qmd
        text: Home
      - href: index.qmd
        text: Presentations

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

