project:
  type: website

website:
  reader-mode: true
  open-graph: true
  page-navigation: true
  page-footer:
    right: 
      - icon: github
        text: GitHub
        href: https://github.com/zekaptain
      - icon: twitter
        text: Twitter
        href: https://twitter.com/zf_elkins
      - icon: envelope-fill
        text: Email
        href: "mailto:zfelkins@proton.me"
  title: "Zoe F. Elkins"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Presentations"
        file: about.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Contact"
        file: contact.qmd
  sidebar:
    - title: "Presentations"
    - title: "Projects"
      style: "docked"
      background: light
      contents:
        - projects.qmd
    - title: "Contact"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

