---
title: "Selected presentations & publications"
---

------------------------------------------------------------------------

## Publications

| **The genetic basis of exploration behavior in a multiparent population of *D. melanogaster***
| *Z. Elkins, A. Rahman, L. Storks, E.G. King*
| In preparation

| **Starvation resistance in an evolved multiparent population of *D. melanogaster***
| *Z. Elkins, J. Moaton, E.G. King*
| In preparation

| [**Identifying splice sites of messenger RNA using support vector machines**](MICS_2016_paper_18.pdf)
| *P. Diamond, Z. Elkins, K. Huff, L. Naylor, S. Schoeberle, S. White, T. Urness, M. Zwier*
| Midwest Instruction and Computing Symposium
| 2016

## Presentations

| **The genetic basis and evolution of complex traits in *Drosophila melanogaster***
| *Z. Elkins*
| Life Sciences Fellowship Talk
| 2021

| **Dietary impact on starvation resistance in an evolved multiparent population of *D. melanogaster***
| *Z. Elkins, J. Moaton, E. King*
| Poster presentation -- The Allied Genetics Conference
| 2020

| **Escaping the warming climate: from penguins to fruit flies**
| *Z. Elkins*
| Public lecture - Daniel Boone Regional Library
| 2019

| **The genetic basis of exploration behavior in a multiparent population of *D. melanogaster***
| *Z. Elkins, A. Rahman, L. Storks, E. King*
| Population, Evolution and Quantitative Genetics Conference
| 2018
